### PR TITLE
remove root requirement, uses git master branch

### PR DESCRIPTION
**Pull request by ManuGithubSteam**
- Removes the requirement to be root and install stuff into the system, all in local folders now
- Commented Ubuntu/Debain specific stuff, please see the comments to install the required dependencies, should work on any linux but you have to install the dependencies by yourself
- Uses master branch of Jentos
- Better nameing ?

### CODE REVIEW

**Comment by malublu** [comment]
Hey thanks for the pull request, but i think the script not works with the travis buil system in the jentos ide ;)
Also Jentos is inactive!

**Comment by ManuGithubSteam** [comment]
Thanks for the reply.
Do you know any better IDE for monkey on Linux ? For now Jentos is still the best i believe...
Thanks

**Comment by malublu** [comment]
Hey no problem ;) sorry for the slow reply.
Because of de vacation, I've forgotten it.

> now any better IDE for monkey

No sorry :/ and I think it comes no more, because monkey2

Also i don't use monkey anymore, because i have a better alternative.
You are from Germany?
And Social Worker with GEEK Hobbies ... cool 👍 
I'm also a voluntary Social Worker ^^

**Comment by ManuGithubSteam** [comment]
What do you use now ?
Yes im from Germany. 
Do you think jentos will be adaped to monkey2. Is monkey2 already useable ?

**Comment by malublu** [comment]
I use haxe + kha

> Do you think jentos will be adaped to monkey2

No. The main developer says that he don't start it.

If you have more question, you can contact me here:
https://kiwiirc.com/client/irc.ktxsoftware.com/#kha

**Pull request closed without merging**
